CREATE TABLE CLINIC(
    reg_num VARCHAR(10) NOT NULL PRIMARY KEY DEFAULT NEWID(),
    name VARCHAR(128),
    address VARCHAR(128),
    phone_number VARCHAR(15),
);
GO
CREATE TABLE PATIENTS(
    pid INTEGER NOT NULL IDENTITY,
    lname VARCHAR(32),
    mname VARCHAR(32),
    fname VARCHAR(32),
    hc_num VARCHAR(32),
    policy_num VARCHAR(32),
    phone_number VARCHAR(32),
    p_email VARCHAR(128),
    PRIMARY KEY(pid),
    UNIQUE(hc_num)
);
GO
CREATE TABLE APPOINTMENT(
    appid INTEGER NOT NULL IDENTITY,
    time datetime,
    PRIMARY KEY(appid)
);
GO
CREATE TABLE HEALTHCARE_PERSONNEL(
    empid INT NOT NULL IDENTITY,
    lname VARCHAR(30) NOT NULL,
    fname VARCHAR(30) NOT NULL,
	Password VARCHAR(63) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    salary MONEY NOT NULL,
    email VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY(empid)
);
GO
CREATE TABLE GOES_TO(
    pid INTEGER NOT NULL,
    reg_num VARCHAR(10) NOT NULL,
    FOREIGN KEY(pid) REFERENCES PATIENTS(pid),
    FOREIGN KEY(reg_num) REFERENCES CLINIC(reg_num)
);
GO
CREATE TABLE HAS(
    pid INTEGER NOT NULL,
    appid INTEGER NOT NULL,
    FOREIGN KEY(pid) REFERENCES PATIENTS(pid),
    FOREIGN KEY(appid) REFERENCES APPOINTMENT(appid)
);
GO
CREATE TABLE WORKS_FOR(
    empid INT NOT NULL,
    reg_num VARCHAR(10) NOT NULL,
    FOREIGN KEY (empid) REFERENCES HEALTHCARE_PERSONNEL(empid),
    FOREIGN KEY (reg_num) REFERENCES CLINIC(reg_num),
);
GO
CREATE TABLE ATTENDS(
    appid INT NOT NULL,
    empid INT NOT NULL,
    FOREIGN KEY (empid) REFERENCES HEALTHCARE_PERSONNEL(empid),
    FOREIGN KEY (appid) REFERENCES APPOINTMENT(appid),
);